### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'RNPreferenceManager.set')

### ISSUE THREAD

**Issue by umakantp** [shimohq/react-native-preference#3]
I'm getting above error with latest react native version:-

TypeError: undefined is not an object (evaluating 'RNPreferenceManager.set')

in line no 43 in file index.js

**Comment by kalyanijamunkar10** [comment]
+1

**Comment by kalyanijamunkar10** [comment]
have you got any solution @umakantp

**Comment by ghsdh3409** [comment]
This issue is currently fixed on v1.1.1. But, it is not released through npm yet.
So, try to install from this repo directly.

**Comment by Gitdart** [comment]
fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
