### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by kalyanijamunkar10** [shimohq/react-native-preference#9]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String im.shimo.react.preference.SharedPreferencesDelegate.get(java.lang.String, java.lang.String)' on a null object reference

**Comment by balbirsng** [comment]
I am also facing the issue, any luck with the issue fix?

**Comment by kalyanijamunkar10** [comment]
@balbirsng Using AsyncStorage for now.

**Comment by magicismight** [comment]
Duplicated with #10
